### ISSUE TITLE
How to find new memory addresses?

### ISSUE THREAD

**Issue by markisus** [spxtr/p3#2]
Can you add some documentation on how you discovered the memory addresses? I would like to add player one and player two positions.

**Comment by jabdownsmash** [comment]
[Here is where the info comes from.](https://docs.google.com/spreadsheets/d/1JX2w-r2fuvWuNgGb6D3Cs4wHQKLFegZe2jhbBuIhCG8/edit#gid=12)

**Comment by markisus** [comment]
Very useful, thanks!
