### ISSUE TITLE
p3 crashes if any address is not within enum boundaries

### ISSUE THREAD

**Issue by jabdownsmash** [spxtr/p3#8]
For global addresses, this will likely not be an issue, but this is an issue for `player[i].action_state` and will be for any addresses that chase pointers. If a game ends, the pointer isn't guaranteed to be pointing at char data anymore, and p3 ends up trying to parse some random value from the memory into the `action_state` fields, and the `ActionState` enum conversion fails. 

For `action_state` specifically, a solution would be to ignore these addresses from Dolphin if `menu` isn't `Game`, but implementing a solution like that might not work for all addresses. A more general but less predictable solution would be to set the field to the default value when the enum conversion error is caught.

**Comment by spxtr** [comment]
Ah right, this was an issue lurking in the back of my mind that I didn't want to acknowledge. Are you going to work on a fix? It should hopefully be a simple check. I'd be fine with resetting to the default.

**Comment by jabdownsmash** [comment]
Enums are pretty limited in python it seems. The simplest fix looks like this:

``` python
def handle(value):
    transformed = (struct.unpack('>i', value)[0] >> shift) & mask
    wrapped = transformed
    if wrapper is not None:
        try:
            wrapper(transformed)
        except:
            wrapper = default
    setattr(obj, name, wrapped)
```

Little weird to handle it that way, but it makes sense to revert to default if the wrapper throws an error. An alternative would be to use a customized class instead of `Enum` and pass in a validation function to the handlers.

**Comment by spxtr** [comment]
I think the simple fix is fine, but make sure to do `except ValueError:`, update the comment saying that the wrapper should raise `ValueError` in case the input is bad, and add a test :)
